# Generated by Django 5.2.7 on 2025-10-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
